### PR TITLE
Add tests for MOSSE and MOBSE

### PR DESCRIPTION
**Pull request by rieder**
Tests copied from SSE and BSE, only modified to change codename. 
They will need to be adapted to reflect code differences.

### CODE REVIEW

**Comment by rieder** [comment]
Great, that test checks out nicely. I've moved it to the tests directory, replacing the BSE copy.

**Comment by rieder** [comment]
Please let me know if you need help with the MOSSE test, I think it's the only thing that needs to be added before we can merge this back into the AMUSE master.

**Comment by GiacobboNicola** [comment]
Hi @rieder.
Sorry for the delay. I have loaded the MOSSE test. 
Thanks

**Comment by GiacobboNicola** [comment]
@rieder I wrote some tests for MOSSE. They are in amuse/src/amuse/community/mosse/test_mosse.py

**Comment by GiacobboNicola** [comment]
Hi @rieder, I don't know how to proceed now. Have I to accept your merger request (this one) in order to add MOBSE and MOSSE in AMUSE? 
Thanks.

**Comment by rieder** [comment]
Hi @GiacobboNicola, can you merge this pull request? It moves the test files to the correct folder.

**Comment by GiacobboNicola** [comment]
Hi @rieder, done.

**Pull request merged**
